/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Balls;

import Balls.NewJFrame1.Ball;
import static Balls.NewJFrame1.BOARD_HIGHT;
import static Balls.NewJFrame1.BOARD_WIDTH;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.util.List;

/**
 *
 * @author Karol
 */
public class game extends javax.swing.JPanel {

    /**
     * Creates new form game
     */
    List<Ball> balls;
    
    public game(List<Ball> balls) {
        initComponents();
        this.balls = balls;
        setPreferredSize(new Dimension(BOARD_WIDTH,BOARD_HIGHT));
        //setSize(BOARD_WIDTH, BOARD_HIGHT);
        this.setBackground(Color.white);
        
        
    }
    
    @Override
    protected void paintComponent(Graphics g) {
        super.paintComponent(g);               
        Graphics2D g2d = (Graphics2D) g;
        
        g2d.drawRect(0, 0, NewJFrame1.BOARD_WIDTH, NewJFrame1.BOARD_HIGHT);
        for(Ball ball : balls)
        {
            g2d.setColor(ball.color);
            g2d.fillOval((int)(ball.x - (ball.width / 2)), (int)(ball.y - ball.hight / 2), ball.width , ball.hight);
        }
        
        //g2d.fillRect(10, 10, 100, 100);
 
        // prostokat
        //g2d.drawRect(10, 10, 380, 380);
        // kolo
        //g2d.drawOval(10, 10, 380, 380);
    }
    
    public void draw()
    {
        
    }




    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
